blank_issues_enabled: true

contact_links:
  - name: GitHub Discussions
    url: https://github.com/telekom/citykey-ios/discussions
    about: Contribute to our discussions on GitHub, e.g. by asking questions and answering already open ones.
    
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/citykey
    about: Ask and answer usage questions on Stack Overflow.

  - name: Discord server
    url: X
    about: Developers and users of the CityKey iOS App can be found on the Discord server.
