# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

name: Continuous Integration (CI)

on:
    workflow_dispatch:

    push:
        branches: [ main ]
        paths:
            - '.github/workflows/swiftlint.yml'
            - '.swiftlint.yml'
            - '**/*.swift'

    pull_request:
        branches: [ main ]
        types: [opened, reopened, synchronize]
        paths:
            - '.github/workflows/swiftlint.yml'
            - '.swiftlint.yml'
            - '**/*.swift'


jobs:

    swift-lint:
      runs-on: ubuntu-24.04

      steps:
        - name: "Checkout repository"
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        - name: "Set up Xcode"
          uses: mxcl/xcodebuild@2cf0ec52b855fa777531c5c89b714caa7a3abd5e # v3.4.0
          with:
            action: none

        - name: "Set up Ruby"
          uses: ruby/setup-ruby@32110d4e311bd8996b2a82bf2a43b714ccc91777 # v1.221.0
          with:
            ruby-version: '3.0'
            bundler-cache: true

        - name: "Fastline SwiftLint"
          uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7 # v3.1.0
          with:
            lane: lint


    unit-tests:
        runs-on: macos-15
        permissions:
            contents: write

        strategy:
            matrix:
                platform:
                    - iOS
                platform-version:
                    - ^15
                    - ^16
                    - ^17
                    - ^18

        steps:
            - name: "Checkout repository"
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: "Set up Xcode"
              uses: mxcl/xcodebuild@2cf0ec52b855fa777531c5c89b714caa7a3abd5e # v3.4.0
              with:
                platform: ${{ matrix.platform }}
                platform-version: ${{ matrix.platform-version }}
                action: none

            - name: "Set up Ruby"
              uses: ruby/setup-ruby@32110d4e311bd8996b2a82bf2a43b714ccc91777 # v1.221.0
              with:
                ruby-version: '3.0'
                bundler-cache: true

            - name: "Run fastlane unit tests with coverage"
              uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7 # v3.1.0
              with:
                lane: test

            - name: "Upload coverage to codecov"
              uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                flags: unit-tests
                fail_ci_if_error: true

            - name: "Upload test artifacts"
              uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
              with:
                name: test-results
                path: /fastlane/test_output


    build-debug:
        runs-on: macos-15
        needs: unit-tests
        timeout-minutes: 60
        permissions:
            contents: write

        strategy:
            matrix:
                platform:
                    - iOS
                platform-version:
                    - ^15
                    - ^16
                    - ^17
                    - ^18

        steps:
            - name: "Checkout repository"
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: "Set up Ruby"
              uses: ruby/setup-ruby@32110d4e311bd8996b2a82bf2a43b714ccc91777 # v1.221.0
              with:
                ruby-version: '3.0'
                bundler-cache: true

            - name: "Build App in Debug Mode"
              uses: mxcl/xcodebuild@2cf0ec52b855fa777531c5c89b714caa7a3abd5e # v3.4.0
              with:
                platform: ${{ matrix.platform }}
                platform-version: ${{ matrix.platform-version }}
                action: test
                code-coverage: true
                warnings-as-errors: false
                configuration: release
                upload-logs: true

            - name: "Archive Debug Build"
              uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
              with:
                path: ./**/*.ipa